### ISSUE TITLE
missing a dot in `SimditorButton` 

### ISSUE THREAD

**Issue by hardywu** [huyinghuan/simditor-marked#2]
Simditor api may have changed. 
`SimditorButton` -> 'Simditor.Button'

**Comment by huyinghuan** [comment]
Thanks , I am repairing it now.

**Comment by huyinghuan** [comment]
已修复. 并且支持最新的simdtor版本.支持AMD．详细请查看 https://github.com/huyinghuan/simditor-marked/blob/master/index.html 和https://github.com/huyinghuan/simditor-marked/blob/master/index-require.html
